### Why use NumPy?
- Python lists are excellent, general-purpose containers. They can be “heterogeneous”, 
- meaning that they can contain elements of a variety of types, and they are quite fast 
- when used to perform individual operations on a handful of elements.

- NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

#### What is an “array”?
- In computer programming, an array is a structure for storing and retrieving data.
- we might visualize a “one-dimensional” array like a list:
- A two-dimensional array would be like a table:
- A three-dimensional array would be like a set of tables

In [3]:
import numpy as np

### Array attributes
- This section covers the ndim, shape, size, and dtype attributes of an array.

### ndim
- The number of dimensions of an array is contained in the ndim attribute.

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.ndim

2

### shape
- The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [5]:
a.shape

(3, 4)

In [6]:
len(a.shape) == a.ndim

True

### size
- The fixed, total number of elements in array is contained in the size attribute.

In [7]:
a.size

12

### dtype
- Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. 
- The data type is recorded in the dtype attribute.

In [8]:
a.dtype

dtype('int32')

## How to create a basic array

- np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

- The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [13]:
# You can create an array with a range of elements:
np.arange(4) 

array([0, 1, 2, 3])

- an array that contains a range of evenly spaced intervals. 
- To do this, you will specify the first number, last number, and the step size.

In [14]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

- You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [15]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
# you can explicitly specify which data type you want using the dtype keyword
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

### Adding, removing, and sorting elements

In [18]:
# adding the element into array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
# sorting the array elements
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
# Concatinating two array into single array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# error because dim of array should same.
np.concatenate((x, y), axis=1)

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[7,8]])

np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### reshape()
- Using arr.reshape() will give a new shape to an array without changing the data. 
- Just remember that when you use the reshape method, the array you want to produce needs to 
- have the same number of elements as the original array.

In [26]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [29]:
# You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])